version: '3'

services:
  postgres:
    image: postgres:13.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ../../sql/meters_table.sql:/docker-entrypoint-initdb.d/create_tables.sql

  meters:
    build:
      context: ../../
      dockerfile: docker/prod/meters_service.dockerfile

    restart: always
    environment:
      - DB_STRING=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
    ports:
      - '8080:8080'